version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jamajoint_app
    container_name: jamajoint_app
    restart: unless-stopped
    working_dir: /var/www/html/jamajoint  
    volumes:
      - .:/var/www/html/jamajoint
    networks:
      - app-network
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: jamajoint_webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/jamajoint  
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: jamajoint_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: jamajoint
      MYSQL_ROOT_PASSWORD: R3li@bleR00tP@ssw0rd!
      MYSQL_USER: jamajoint_user
      MYSQL_PASSWORD: J@maJ0int_UsrP@ssw0rd!
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
